// export HelloWorld for npm package
export { greet } from './modules/challenges/hello-world';
export { HelloWorld } from './modules/challenges/hello-world';
export { wordCount } from './modules/challenges/word-count';
export { Squares } from './modules/challenges/difference-of-squares';
export { Gigasecond } from './modules/challenges/gigasecond';
export { reverse } from './modules/challenges/reverse-string';
export { Triangle } from './modules/challenges/triangle';
export { steps } from './modules/challenges/collatz-conjecture';